### ISSUE TITLE
Update Architecture Design

### ISSUE THREAD

**Issue by DracoDrakthen** [COS420-Fall23/Team-D#117]
The comments from Deliverable 4 must be addressed.

For any comment that was not addressed, deduct -2 points.

This will most likely be a MVC architecture. You can use[ this as a template](https://docs.google.com/document/d/1S7R3Tt6wKMN1nIgka4z8HZBGtxmpXdrA/edit), but your team will need to fill in your specific technologies and other information specific for your app. The example is for an online shopping system.

A UML package diagram showing the system architecture, where the basic classes/system entities are located, and associations.

If the classes, associations, system architecture are not properly shown, deduct -7.5 points.

The name of the classes, packages, etc should match the application under the development. If not, deduct -2 points for each mismatch.

The description of the architecture and the justification of the chosen architecture.

If the description is missing or does not make sense, deduct -7.5 points.

If the reason to choose this specific architecture does not make sense, deduct -7.5 points.

**Comment by GShadow5** [comment]
There is no feedback on the architecture document from D3 to fix. It got 5/5 points
