### ISSUE TITLE
Use Case Models

### ISSUE THREAD

**Issue by ngauthier404** [COS420-Fall23/Team-D#15]
You are expected to have about 10 – 20 Use Case Descriptions and 2 – 4 Use Case Diagrams (you can use Miro or other diagramming software to make them).  
Pick a few of the main features of your application that you would like to begin developing first,  and based on their FR/NFR, create use case descriptions and diagrams for them.
One of your use case diagrams should contain most/all the use cases in your system.

**Comment by greglnelson** [comment]
@sethlvaughn are you doing all of these? that's not reasonable amount of work for one person?
