### ISSUE TITLE
New Version of Application pt 2

### ISSUE THREAD

**Issue by DracoDrakthen** [COS420-Fall23/Team-D#173]
Record a short 1-6 minute video showing the progress your team has made, walking through, for each feature, the user story/use case/mockup, tests, then code, then website in the browser, and people contributing to the development for each.

If this video is missing, -15 points

Show the scoping diagrams/documents from our scoping meeting and update them with % progress

Your video must show you going over the user story/use case/mockup, tests, then code, then website in the browser showing that feature. Your code showing that you have tests. Otherwise, -7.5 points as specified above. I will be strict about this! Be sure to show the tests you wrote instead of just running them (I will use the CI results to check the tests pass).

This is meant to simulate the demo that happens with the Product Owner and stakeholders in an industry sprint review

[Here is an example video from Deliverable 4](https://drive.google.com/file/d/1IATYjewAbMztvHS62CvGhoo104H1gKei/view?usp=drive_link) from Team D Fall 23.  Starting 0min 34seconds is a good example for a single feature. Be sure to show the test code for each feature and briefly explain them, don’t just show that tests run. (Note that this was recorded before the scoping meetings so the example video is lacking showing that document and updates on progress.)

If the working web application is so far behind it’s UI does not resemble  your application, -30 points

If login is not finished, -10 points

The developers should read this and are expected to, as needed, review/complete parts of the [Interactive React Textbook](https://greglnelson.github.io/react-hooks-typescript-tome/) earlier than other team members. 

All team members are expected to do self-directed learning using Google, StackOverflow, other online resources, and ask people or other classmates questions. Developers are expected to help any other team members with technical questions.

Use the example applications found/submitted from Assignment 4 to help you here

Communicate with other teams to get help with problems and advice, using Discord. Your team may use their code/resources like any other resources, just requiring citation.

Setting up the build environments and the necessary dependencies.  

Your README file should detail the installation and build process for your application. Make sure it works on each person’s machine.

If there is nothing, -10 points.

You must upload a video to your team Discord channel in the COS420 Discord, from a synchronous team meeting/screenshare on Discord or Zoom, where each team member shares their screen showing the app working on their machine, to show that this has been set up and works for each team member. No video editing, one person on the team should record their screen continuously through the meeting (you can use the Zoom record meeting feature to do this easily).

Previous submission of the video counts if all team members were present

Your team’s short 1-6 minute video counts if all team members show they did some code and show the app running on their machine

If this is not present, -20 points.

For each team member not showing it works on their machine, -10 points

If you’re having trouble here, get help early and often by asking questions in the #question channel.

**Comment by GShadow5** [comment]
video done
