### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by DracoDrakthen** [COS420-Fall23/Team-D#2]
I will have Kaleb, Seth, and Ethan on this. Please write about 10 new user stories based on the updated problem statement. This will allow us to split up the work and be able to get this done by Monday. Again if any issues arise please let Devon know so he can assist. Ethan if you could revise the user stories from a design perspective that would be greatly appreciated.

**Comment by sethlvaughn** [comment]
I have added 10 new user stories based on the updated problem statement in the following google doc:

https://docs.google.com/document/d/1GhgWla-ShadIFyXL35oG9Yytex1SpgJFiX7aFVdd0L4/edit?usp=sharing
