### ISSUE TITLE
Research open-source packages for scraping jobs

### ISSUE THREAD

**Issue by K-Hannan12** [COS420-Fall23/Team-D#31]

**Comment by K-Hannan12** [comment]
I'm looking for some libraries to try scraping job sites with, and I've found a couple. I found [jobberjs](https://www.npmjs.com/package/jobberjs) which works with both LinkedIn and Indeed, but it hasn't been updated in 3 years and may not work anymore; I'll need to test it out soon. Then, [indeed-job-scraper](https://www.npmjs.com/package/indeed-job-scraper) is another potential option, however based on the documentation I believe this one is designed more for command-line usage and not browser usage, as it may require running its own browser instance to work; again, needs some potential testing.

**Comment by K-Hannan12** [comment]
So I have worked with both jobberjs and indeed-job-scraper. I found jobberjs difficult to work with in React and wasn't able to get it working, however my experience with React and Node is limited so someone else may be able to get it working. The other, indeed-job-scraper does not work at all in React.

I tried another one, being [job-scraper](https://www.npmjs.com/package/job-scraper), since it looked like it would work well in React, however it appears to be outdated and not working at the moment.

**Comment by C-Nubela** [comment]
Have you guys taken a look at the [LinkedIn API ](https://github.com/tomquirk/linkedin-api)project yet?

Alternatively, if that won't work for you, I work at Proxycurl, a B2B data provider, and you could definitely accomplish this with our API. [Here's an article about it](https://nubela.co/blog/the-ultimate-guide-to-proxycurls-linkedin-jobs-api-with-sample-code/?utm_campaign=content_amplification&utm_source=reddit&utm_medium=social&utm_content=comments).
