### ISSUE TITLE
prior solutions revision

### ISSUE THREAD

**Issue by DracoDrakthen** [COS420-Fall23/Team-D#4]
This will be for the project description document. If I could have Kaleb, Devon, and Nick go over the prior sites we discussed for it and how our app is different that would be awesome. Could be over indeed, LinkedIn, ZipRecruiter, etc. I suggest making a task flow in miro, this way we can just import the image.

**Comment by K-Hannan12** [comment]
I did a Prior Solution on LinkedIn and made a miro board for the prior solutions.
https://miro.com/app/board/uXjVNf1Xqls=/?share_link_id=84568241948

**Comment by DracoDrakthen** [comment]
I have completed prior solution 2 on indeed, also used the miro link to make a task flow diagram. 
https://miro.com/app/board/uXjVNf1Xqls=/?share_link_id=58033011259
