### ISSUE TITLE
Updating user stories

### ISSUE THREAD

**Issue by DracoDrakthen** [COS420-Fall23/Team-D#5]
Please use the feedback provided to us by Dr.Greg. Please use that as a reference to improve the user stories.

**Comment by K-Hannan12** [comment]
https://docs.google.com/document/d/1WW1GEdfVlKb9ndyQAqJQIynkf1h6FQNQRKu-MQ9hDoU/edit

**Comment by ngauthier404** [comment]
I went to go work on our functional requirements, based on our user stories, and it appears these user stories are not aligned with the direction we decided to take the project based on our meeting on October 7th. They will need to be updated further.

**Comment by K-Hannan12** [comment]
I started to remove some of the stories that do not align with our idea but I am having a hard time coming up with new ones to replace the old ones that I have removed.

**Comment by K-Hannan12** [comment]
Created PR for adding the User stories to the Documents Folder.
