### ISSUE TITLE
10-15 non-functional requirements

### ISSUE THREAD

**Issue by DracoDrakthen** [COS420-Fall23/Team-D#8]
Please fill out the non-functional requirements in this template here https://docs.google.com/document/d/1l9BqjtyLnCjNHyYV54ADELYubQxLMehp/edit

**Comment by sethlvaughn** [comment]
I have finished the non-functional requirements in the following doc:

https://docs.google.com/document/d/15N1_L_n0KK8nobURMHlwYlPECSnGzS2S/edit?usp=sharing&ouid=104934514094606313112&rtpof=true&sd=true
